/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var NullPmd_pb = require('./NullPmd_pb.js');
goog.exportSymbol('proto.propertyPmd.tagPropertyItem_s2c', null, global);
goog.exportSymbol('proto.propertyPmd.tagPropertyRelatItem_s2c', null, global);
goog.exportSymbol('proto.propertyPmd.tagPropertySubItem_s2c', null, global);
goog.exportSymbol('proto.propertyPmd.tagPropertyTypeItem_s2c', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.propertyPmd.tagPropertyTypeItem_s2c = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.propertyPmd.tagPropertyTypeItem_s2c, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.propertyPmd.tagPropertyTypeItem_s2c.displayName = 'proto.propertyPmd.tagPropertyTypeItem_s2c';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.toObject = function(opt_includeInstance) {
  return proto.propertyPmd.tagPropertyTypeItem_s2c.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.propertyPmd.tagPropertyTypeItem_s2c} msg The msg instance to transform.
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.toObject = function(includeInstance, msg) {
  var f, obj = {
    respcmd: (f = msg.getRespcmd()) && NullPmd_pb.response.toObject(includeInstance, f),
    dwtypeid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    dwsortid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sztypename: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.propertyPmd.tagPropertyTypeItem_s2c}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.propertyPmd.tagPropertyTypeItem_s2c;
  return proto.propertyPmd.tagPropertyTypeItem_s2c.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.propertyPmd.tagPropertyTypeItem_s2c} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.propertyPmd.tagPropertyTypeItem_s2c}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new NullPmd_pb.response;
      reader.readMessage(value,NullPmd_pb.response.deserializeBinaryFromReader);
      msg.setRespcmd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwtypeid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwsortid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSztypename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.propertyPmd.tagPropertyTypeItem_s2c.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.propertyPmd.tagPropertyTypeItem_s2c} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRespcmd();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      NullPmd_pb.response.serializeBinaryToWriter
    );
  }
  f = message.getDwtypeid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDwsortid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getSztypename();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional NullPmd.response respcmd = 1;
 * @return {?proto.NullPmd.response}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.getRespcmd = function() {
  return /** @type{?proto.NullPmd.response} */ (
    jspb.Message.getWrapperField(this, NullPmd_pb.response, 1));
};


/** @param {?proto.NullPmd.response|undefined} value */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.setRespcmd = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.clearRespcmd = function() {
  this.setRespcmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.hasRespcmd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 dwtypeid = 2;
 * @return {number}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.getDwtypeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.setDwtypeid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 dwsortid = 3;
 * @return {number}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.getDwsortid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.setDwsortid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string sztypename = 4;
 * @return {string}
 */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.getSztypename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.propertyPmd.tagPropertyTypeItem_s2c.prototype.setSztypename = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.propertyPmd.tagPropertyRelatItem_s2c = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.propertyPmd.tagPropertyRelatItem_s2c, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.propertyPmd.tagPropertyRelatItem_s2c.displayName = 'proto.propertyPmd.tagPropertyRelatItem_s2c';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.toObject = function(opt_includeInstance) {
  return proto.propertyPmd.tagPropertyRelatItem_s2c.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.propertyPmd.tagPropertyRelatItem_s2c} msg The msg instance to transform.
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.toObject = function(includeInstance, msg) {
  var f, obj = {
    respcmd: (f = msg.getRespcmd()) && NullPmd_pb.response.toObject(includeInstance, f),
    dwpropertyid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    dwtypeid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.propertyPmd.tagPropertyRelatItem_s2c}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.propertyPmd.tagPropertyRelatItem_s2c;
  return proto.propertyPmd.tagPropertyRelatItem_s2c.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.propertyPmd.tagPropertyRelatItem_s2c} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.propertyPmd.tagPropertyRelatItem_s2c}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new NullPmd_pb.response;
      reader.readMessage(value,NullPmd_pb.response.deserializeBinaryFromReader);
      msg.setRespcmd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwpropertyid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwtypeid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.propertyPmd.tagPropertyRelatItem_s2c.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.propertyPmd.tagPropertyRelatItem_s2c} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRespcmd();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      NullPmd_pb.response.serializeBinaryToWriter
    );
  }
  f = message.getDwpropertyid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDwtypeid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
};


/**
 * optional NullPmd.response respcmd = 1;
 * @return {?proto.NullPmd.response}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.getRespcmd = function() {
  return /** @type{?proto.NullPmd.response} */ (
    jspb.Message.getWrapperField(this, NullPmd_pb.response, 1));
};


/** @param {?proto.NullPmd.response|undefined} value */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.setRespcmd = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.clearRespcmd = function() {
  this.setRespcmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.hasRespcmd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 dwpropertyid = 2;
 * @return {number}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.getDwpropertyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.setDwpropertyid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 dwtypeid = 3;
 * @return {number}
 */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.getDwtypeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyRelatItem_s2c.prototype.setDwtypeid = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.propertyPmd.tagPropertyItem_s2c = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.propertyPmd.tagPropertyItem_s2c, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.propertyPmd.tagPropertyItem_s2c.displayName = 'proto.propertyPmd.tagPropertyItem_s2c';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.toObject = function(opt_includeInstance) {
  return proto.propertyPmd.tagPropertyItem_s2c.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.propertyPmd.tagPropertyItem_s2c} msg The msg instance to transform.
 * @return {!Object}
 */
proto.propertyPmd.tagPropertyItem_s2c.toObject = function(includeInstance, msg) {
  var f, obj = {
    dwpropertyid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dwpropertykind: jspb.Message.getFieldWithDefault(msg, 2, 0),
    cbusearea: jspb.Message.getFieldWithDefault(msg, 3, 0),
    cbservicearea: jspb.Message.getFieldWithDefault(msg, 4, 0),
    cbrecommend: jspb.Message.getFieldWithDefault(msg, 5, 0),
    dwexchangeratio: jspb.Message.getFieldWithDefault(msg, 6, 0),
    lpropertydiamond: jspb.Message.getFieldWithDefault(msg, 7, 0),
    lpropertygold: jspb.Message.getFieldWithDefault(msg, 8, 0),
    dpropertycash: +jspb.Message.getFieldWithDefault(msg, 9, 0.0),
    lpropertyusermedal: jspb.Message.getFieldWithDefault(msg, 10, 0),
    lpropertyloveliness: jspb.Message.getFieldWithDefault(msg, 11, 0),
    lsendloveliness: jspb.Message.getFieldWithDefault(msg, 12, 0),
    lrecvloveliness: jspb.Message.getFieldWithDefault(msg, 13, 0),
    luseresultsgold: jspb.Message.getFieldWithDefault(msg, 14, 0),
    dwuseresultsvalidtime: jspb.Message.getFieldWithDefault(msg, 15, 0),
    dwuseresultsvalidtimescoremultiple: jspb.Message.getFieldWithDefault(msg, 16, 0),
    dwuseresultsgiftpackage: jspb.Message.getFieldWithDefault(msg, 17, 0),
    dwsortid: jspb.Message.getFieldWithDefault(msg, 18, 0),
    szname: jspb.Message.getFieldWithDefault(msg, 19, ""),
    szregulationsinfo: jspb.Message.getFieldWithDefault(msg, 20, ""),
    respcmd: (f = msg.getRespcmd()) && NullPmd_pb.response.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.propertyPmd.tagPropertyItem_s2c}
 */
proto.propertyPmd.tagPropertyItem_s2c.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.propertyPmd.tagPropertyItem_s2c;
  return proto.propertyPmd.tagPropertyItem_s2c.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.propertyPmd.tagPropertyItem_s2c} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.propertyPmd.tagPropertyItem_s2c}
 */
proto.propertyPmd.tagPropertyItem_s2c.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwpropertyid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwpropertykind(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCbusearea(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCbservicearea(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCbrecommend(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwexchangeratio(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLpropertydiamond(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLpropertygold(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDpropertycash(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLpropertyusermedal(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLpropertyloveliness(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLsendloveliness(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLrecvloveliness(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLuseresultsgold(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwuseresultsvalidtime(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwuseresultsvalidtimescoremultiple(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwuseresultsgiftpackage(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwsortid(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzname(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzregulationsinfo(value);
      break;
    case 21:
      var value = new NullPmd_pb.response;
      reader.readMessage(value,NullPmd_pb.response.deserializeBinaryFromReader);
      msg.setRespcmd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.propertyPmd.tagPropertyItem_s2c.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.propertyPmd.tagPropertyItem_s2c} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.propertyPmd.tagPropertyItem_s2c.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDwpropertyid();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getDwpropertykind();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getCbusearea();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCbservicearea();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getCbrecommend();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getDwexchangeratio();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getLpropertydiamond();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getLpropertygold();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getDpropertycash();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getLpropertyusermedal();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getLpropertyloveliness();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
  f = message.getLsendloveliness();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getLrecvloveliness();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
  f = message.getLuseresultsgold();
  if (f !== 0) {
    writer.writeUint64(
      14,
      f
    );
  }
  f = message.getDwuseresultsvalidtime();
  if (f !== 0) {
    writer.writeUint64(
      15,
      f
    );
  }
  f = message.getDwuseresultsvalidtimescoremultiple();
  if (f !== 0) {
    writer.writeUint64(
      16,
      f
    );
  }
  f = message.getDwuseresultsgiftpackage();
  if (f !== 0) {
    writer.writeUint64(
      17,
      f
    );
  }
  f = message.getDwsortid();
  if (f !== 0) {
    writer.writeUint64(
      18,
      f
    );
  }
  f = message.getSzname();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getSzregulationsinfo();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getRespcmd();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      NullPmd_pb.response.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 dwpropertyid = 1;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwpropertyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwpropertyid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 dwpropertykind = 2;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwpropertykind = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwpropertykind = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 cbusearea = 3;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getCbusearea = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setCbusearea = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 cbservicearea = 4;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getCbservicearea = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setCbservicearea = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int32 cbrecommend = 5;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getCbrecommend = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setCbrecommend = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional uint64 dwexchangeratio = 6;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwexchangeratio = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwexchangeratio = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint64 lpropertydiamond = 7;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLpropertydiamond = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLpropertydiamond = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional uint64 lpropertygold = 8;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLpropertygold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLpropertygold = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional double dpropertycash = 9;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDpropertycash = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 9, 0.0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDpropertycash = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional uint64 lpropertyusermedal = 10;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLpropertyusermedal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLpropertyusermedal = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional uint64 lpropertyloveliness = 11;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLpropertyloveliness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLpropertyloveliness = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional uint64 lsendloveliness = 12;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLsendloveliness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLsendloveliness = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional uint64 lrecvloveliness = 13;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLrecvloveliness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLrecvloveliness = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional uint64 luseresultsgold = 14;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getLuseresultsgold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setLuseresultsgold = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional uint64 dwuseresultsvalidtime = 15;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwuseresultsvalidtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwuseresultsvalidtime = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional uint64 dwuseresultsvalidtimescoremultiple = 16;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwuseresultsvalidtimescoremultiple = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwuseresultsvalidtimescoremultiple = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional uint64 dwuseresultsgiftpackage = 17;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwuseresultsgiftpackage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwuseresultsgiftpackage = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * optional uint64 dwsortid = 18;
 * @return {number}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getDwsortid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setDwsortid = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * optional string szname = 19;
 * @return {string}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getSzname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/** @param {string} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setSzname = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * optional string szregulationsinfo = 20;
 * @return {string}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getSzregulationsinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setSzregulationsinfo = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * optional NullPmd.response respcmd = 21;
 * @return {?proto.NullPmd.response}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.getRespcmd = function() {
  return /** @type{?proto.NullPmd.response} */ (
    jspb.Message.getWrapperField(this, NullPmd_pb.response, 21));
};


/** @param {?proto.NullPmd.response|undefined} value */
proto.propertyPmd.tagPropertyItem_s2c.prototype.setRespcmd = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.propertyPmd.tagPropertyItem_s2c.prototype.clearRespcmd = function() {
  this.setRespcmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.propertyPmd.tagPropertyItem_s2c.prototype.hasRespcmd = function() {
  return jspb.Message.getField(this, 21) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.propertyPmd.tagPropertySubItem_s2c = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.propertyPmd.tagPropertySubItem_s2c, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.propertyPmd.tagPropertySubItem_s2c.displayName = 'proto.propertyPmd.tagPropertySubItem_s2c';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.toObject = function(opt_includeInstance) {
  return proto.propertyPmd.tagPropertySubItem_s2c.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.propertyPmd.tagPropertySubItem_s2c} msg The msg instance to transform.
 * @return {!Object}
 */
proto.propertyPmd.tagPropertySubItem_s2c.toObject = function(includeInstance, msg) {
  var f, obj = {
    respcmd: (f = msg.getRespcmd()) && NullPmd_pb.response.toObject(includeInstance, f),
    dwpropertyid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    dwownerpropertyid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dwpropertycount: jspb.Message.getFieldWithDefault(msg, 4, 0),
    dwsortid: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.propertyPmd.tagPropertySubItem_s2c}
 */
proto.propertyPmd.tagPropertySubItem_s2c.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.propertyPmd.tagPropertySubItem_s2c;
  return proto.propertyPmd.tagPropertySubItem_s2c.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.propertyPmd.tagPropertySubItem_s2c} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.propertyPmd.tagPropertySubItem_s2c}
 */
proto.propertyPmd.tagPropertySubItem_s2c.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new NullPmd_pb.response;
      reader.readMessage(value,NullPmd_pb.response.deserializeBinaryFromReader);
      msg.setRespcmd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwpropertyid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwownerpropertyid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwpropertycount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwsortid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.propertyPmd.tagPropertySubItem_s2c.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.propertyPmd.tagPropertySubItem_s2c} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.propertyPmd.tagPropertySubItem_s2c.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRespcmd();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      NullPmd_pb.response.serializeBinaryToWriter
    );
  }
  f = message.getDwpropertyid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDwownerpropertyid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getDwpropertycount();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getDwsortid();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional NullPmd.response respcmd = 1;
 * @return {?proto.NullPmd.response}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.getRespcmd = function() {
  return /** @type{?proto.NullPmd.response} */ (
    jspb.Message.getWrapperField(this, NullPmd_pb.response, 1));
};


/** @param {?proto.NullPmd.response|undefined} value */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.setRespcmd = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.propertyPmd.tagPropertySubItem_s2c.prototype.clearRespcmd = function() {
  this.setRespcmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.hasRespcmd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 dwpropertyid = 2;
 * @return {number}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.getDwpropertyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.setDwpropertyid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 dwownerpropertyid = 3;
 * @return {number}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.getDwownerpropertyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.setDwownerpropertyid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint64 dwpropertycount = 4;
 * @return {number}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.getDwpropertycount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.setDwpropertycount = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint64 dwsortid = 5;
 * @return {number}
 */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.getDwsortid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.propertyPmd.tagPropertySubItem_s2c.prototype.setDwsortid = function(value) {
  jspb.Message.setField(this, 5, value);
};


goog.object.extend(exports, proto.propertyPmd);
