/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.CommonPmd.personinfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CommonPmd.personinfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CommonPmd.personinfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CommonPmd.personinfo.displayName = 'proto.CommonPmd.personinfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CommonPmd.personinfo.prototype.toObject = function(opt_includeInstance) {
  return proto.CommonPmd.personinfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CommonPmd.personinfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.CommonPmd.personinfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    wfaceid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dwuserid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    dwgameid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dwgroupid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    dwcustomid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    dwexperience: jspb.Message.getFieldWithDefault(msg, 6, 0),
    lloveliness: jspb.Message.getFieldWithDefault(msg, 7, 0),
    luserscore: jspb.Message.getFieldWithDefault(msg, 8, 0),
    luserinsure: jspb.Message.getFieldWithDefault(msg, 9, 0),
    luseringot: jspb.Message.getFieldWithDefault(msg, 10, 0),
    duserbeans: +jspb.Message.getFieldWithDefault(msg, 11, 0.0),
    cbgender: jspb.Message.getFieldWithDefault(msg, 12, 0),
    cbmoormachine: jspb.Message.getFieldWithDefault(msg, 13, 0),
    szaccounts: jspb.Message.getFieldWithDefault(msg, 14, ""),
    sznickname: jspb.Message.getFieldWithDefault(msg, 15, ""),
    szdynamicpass: jspb.Message.getFieldWithDefault(msg, 16, ""),
    szgroupname: jspb.Message.getFieldWithDefault(msg, 17, ""),
    cbinsureenabled: jspb.Message.getFieldWithDefault(msg, 18, 0),
    cbshowserverstatus: jspb.Message.getFieldWithDefault(msg, 19, 0),
    cbisagent: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CommonPmd.personinfo}
 */
proto.CommonPmd.personinfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CommonPmd.personinfo;
  return proto.CommonPmd.personinfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CommonPmd.personinfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CommonPmd.personinfo}
 */
proto.CommonPmd.personinfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWfaceid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwuserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwgameid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwgroupid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwcustomid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDwexperience(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLloveliness(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLuserscore(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLuserinsure(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLuseringot(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDuserbeans(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCbgender(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCbmoormachine(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzaccounts(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setSznickname(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzdynamicpass(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzgroupname(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCbinsureenabled(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCbshowserverstatus(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCbisagent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CommonPmd.personinfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CommonPmd.personinfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CommonPmd.personinfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.CommonPmd.personinfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWfaceid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getDwuserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getDwgameid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getDwgroupid();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getDwcustomid();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getDwexperience();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getLloveliness();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getLuserscore();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getLuserinsure();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getLuseringot();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getDuserbeans();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getCbgender();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getCbmoormachine();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
  f = message.getSzaccounts();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getSznickname();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getSzdynamicpass();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getSzgroupname();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getCbinsureenabled();
  if (f !== 0) {
    writer.writeUint64(
      18,
      f
    );
  }
  f = message.getCbshowserverstatus();
  if (f !== 0) {
    writer.writeUint64(
      19,
      f
    );
  }
  f = message.getCbisagent();
  if (f !== 0) {
    writer.writeUint64(
      20,
      f
    );
  }
};


/**
 * optional int32 wfaceid = 1;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getWfaceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setWfaceid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 dwuserid = 2;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDwuserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDwuserid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 dwgameid = 3;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDwgameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDwgameid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint64 dwgroupid = 4;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDwgroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDwgroupid = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint64 dwcustomid = 5;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDwcustomid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDwcustomid = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional uint64 dwexperience = 6;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDwexperience = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDwexperience = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint64 lloveliness = 7;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getLloveliness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setLloveliness = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional uint64 luserscore = 8;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getLuserscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setLuserscore = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional uint64 luserinsure = 9;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getLuserinsure = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setLuserinsure = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional uint64 luseringot = 10;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getLuseringot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setLuseringot = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional double duserbeans = 11;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getDuserbeans = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 11, 0.0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setDuserbeans = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional uint64 cbgender = 12;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getCbgender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setCbgender = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional uint64 cbmoormachine = 13;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getCbmoormachine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setCbmoormachine = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional string szaccounts = 14;
 * @return {string}
 */
proto.CommonPmd.personinfo.prototype.getSzaccounts = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.CommonPmd.personinfo.prototype.setSzaccounts = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional string sznickname = 15;
 * @return {string}
 */
proto.CommonPmd.personinfo.prototype.getSznickname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.CommonPmd.personinfo.prototype.setSznickname = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional string szdynamicpass = 16;
 * @return {string}
 */
proto.CommonPmd.personinfo.prototype.getSzdynamicpass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.CommonPmd.personinfo.prototype.setSzdynamicpass = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional string szgroupname = 17;
 * @return {string}
 */
proto.CommonPmd.personinfo.prototype.getSzgroupname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.CommonPmd.personinfo.prototype.setSzgroupname = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * optional uint64 cbinsureenabled = 18;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getCbinsureenabled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setCbinsureenabled = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * optional uint64 cbshowserverstatus = 19;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getCbshowserverstatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setCbshowserverstatus = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * optional uint64 cbisagent = 20;
 * @return {number}
 */
proto.CommonPmd.personinfo.prototype.getCbisagent = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/** @param {number} value */
proto.CommonPmd.personinfo.prototype.setCbisagent = function(value) {
  jspb.Message.setField(this, 20, value);
};


goog.object.extend(exports, proto.CommonPmd);
