// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealAuthPmd.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RealAuthPmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace RealAuthPmd {
class RealAuthParameter_s2cDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RealAuthParameter_s2c> {
} _RealAuthParameter_s2c_default_instance_;

namespace protobuf_RealAuthPmd_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealAuthParameter_s2c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealAuthParameter_s2c, respcmd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealAuthParameter_s2c, dwauthentdisable_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealAuthParameter_s2c, dwauthrealaward_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(RealAuthParameter_s2c)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_RealAuthParameter_s2c_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "RealAuthPmd.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _RealAuthParameter_s2c_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::NullPmd::protobuf_NullPmd_2eproto::InitDefaults();
  _RealAuthParameter_s2c_default_instance_.DefaultConstruct();
  _RealAuthParameter_s2c_default_instance_.get_mutable()->respcmd_ = const_cast< ::NullPmd::response*>(
      ::NullPmd::response::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\021RealAuthPmd.proto\022\013RealAuthPmd\032\rNullPm"
      "d.proto\"n\n\025RealAuthParameter_s2c\022\"\n\007resp"
      "cmd\030\001 \001(\0132\021.NullPmd.response\022\030\n\020dwauthen"
      "tdisable\030\002 \001(\004\022\027\n\017dwauthrealaward\030\003 \001(\004b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 167);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RealAuthPmd.proto", &protobuf_RegisterTypes);
  ::NullPmd::protobuf_NullPmd_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_RealAuthPmd_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RealAuthParameter_s2c::kRespcmdFieldNumber;
const int RealAuthParameter_s2c::kDwauthentdisableFieldNumber;
const int RealAuthParameter_s2c::kDwauthrealawardFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RealAuthParameter_s2c::RealAuthParameter_s2c()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RealAuthPmd_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RealAuthPmd.RealAuthParameter_s2c)
}
RealAuthParameter_s2c::RealAuthParameter_s2c(const RealAuthParameter_s2c& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_respcmd()) {
    respcmd_ = new ::NullPmd::response(*from.respcmd_);
  } else {
    respcmd_ = NULL;
  }
  ::memcpy(&dwauthentdisable_, &from.dwauthentdisable_,
    reinterpret_cast<char*>(&dwauthrealaward_) -
    reinterpret_cast<char*>(&dwauthentdisable_) + sizeof(dwauthrealaward_));
  // @@protoc_insertion_point(copy_constructor:RealAuthPmd.RealAuthParameter_s2c)
}

void RealAuthParameter_s2c::SharedCtor() {
  ::memset(&respcmd_, 0, reinterpret_cast<char*>(&dwauthrealaward_) -
    reinterpret_cast<char*>(&respcmd_) + sizeof(dwauthrealaward_));
  _cached_size_ = 0;
}

RealAuthParameter_s2c::~RealAuthParameter_s2c() {
  // @@protoc_insertion_point(destructor:RealAuthPmd.RealAuthParameter_s2c)
  SharedDtor();
}

void RealAuthParameter_s2c::SharedDtor() {
  if (this != internal_default_instance()) {
    delete respcmd_;
  }
}

void RealAuthParameter_s2c::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealAuthParameter_s2c::descriptor() {
  protobuf_RealAuthPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RealAuthPmd_2eproto::file_level_metadata[0].descriptor;
}

const RealAuthParameter_s2c& RealAuthParameter_s2c::default_instance() {
  protobuf_RealAuthPmd_2eproto::InitDefaults();
  return *internal_default_instance();
}

RealAuthParameter_s2c* RealAuthParameter_s2c::New(::google::protobuf::Arena* arena) const {
  RealAuthParameter_s2c* n = new RealAuthParameter_s2c;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RealAuthParameter_s2c::Clear() {
// @@protoc_insertion_point(message_clear_start:RealAuthPmd.RealAuthParameter_s2c)
  if (GetArenaNoVirtual() == NULL && respcmd_ != NULL) {
    delete respcmd_;
  }
  respcmd_ = NULL;
  ::memset(&dwauthentdisable_, 0, reinterpret_cast<char*>(&dwauthrealaward_) -
    reinterpret_cast<char*>(&dwauthentdisable_) + sizeof(dwauthrealaward_));
}

bool RealAuthParameter_s2c::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RealAuthPmd.RealAuthParameter_s2c)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .NullPmd.response respcmd = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_respcmd()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 dwauthentdisable = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &dwauthentdisable_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 dwauthrealaward = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &dwauthrealaward_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RealAuthPmd.RealAuthParameter_s2c)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RealAuthPmd.RealAuthParameter_s2c)
  return false;
#undef DO_
}

void RealAuthParameter_s2c::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RealAuthPmd.RealAuthParameter_s2c)
  // .NullPmd.response respcmd = 1;
  if (this->has_respcmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->respcmd_, output);
  }

  // uint64 dwauthentdisable = 2;
  if (this->dwauthentdisable() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->dwauthentdisable(), output);
  }

  // uint64 dwauthrealaward = 3;
  if (this->dwauthrealaward() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->dwauthrealaward(), output);
  }

  // @@protoc_insertion_point(serialize_end:RealAuthPmd.RealAuthParameter_s2c)
}

::google::protobuf::uint8* RealAuthParameter_s2c::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:RealAuthPmd.RealAuthParameter_s2c)
  // .NullPmd.response respcmd = 1;
  if (this->has_respcmd()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->respcmd_, false, target);
  }

  // uint64 dwauthentdisable = 2;
  if (this->dwauthentdisable() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->dwauthentdisable(), target);
  }

  // uint64 dwauthrealaward = 3;
  if (this->dwauthrealaward() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->dwauthrealaward(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RealAuthPmd.RealAuthParameter_s2c)
  return target;
}

size_t RealAuthParameter_s2c::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RealAuthPmd.RealAuthParameter_s2c)
  size_t total_size = 0;

  // .NullPmd.response respcmd = 1;
  if (this->has_respcmd()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->respcmd_);
  }

  // uint64 dwauthentdisable = 2;
  if (this->dwauthentdisable() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dwauthentdisable());
  }

  // uint64 dwauthrealaward = 3;
  if (this->dwauthrealaward() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dwauthrealaward());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RealAuthParameter_s2c::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RealAuthPmd.RealAuthParameter_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  const RealAuthParameter_s2c* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RealAuthParameter_s2c>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RealAuthPmd.RealAuthParameter_s2c)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RealAuthPmd.RealAuthParameter_s2c)
    MergeFrom(*source);
  }
}

void RealAuthParameter_s2c::MergeFrom(const RealAuthParameter_s2c& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RealAuthPmd.RealAuthParameter_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_respcmd()) {
    mutable_respcmd()->::NullPmd::response::MergeFrom(from.respcmd());
  }
  if (from.dwauthentdisable() != 0) {
    set_dwauthentdisable(from.dwauthentdisable());
  }
  if (from.dwauthrealaward() != 0) {
    set_dwauthrealaward(from.dwauthrealaward());
  }
}

void RealAuthParameter_s2c::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RealAuthPmd.RealAuthParameter_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RealAuthParameter_s2c::CopyFrom(const RealAuthParameter_s2c& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RealAuthPmd.RealAuthParameter_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RealAuthParameter_s2c::IsInitialized() const {
  return true;
}

void RealAuthParameter_s2c::Swap(RealAuthParameter_s2c* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RealAuthParameter_s2c::InternalSwap(RealAuthParameter_s2c* other) {
  std::swap(respcmd_, other->respcmd_);
  std::swap(dwauthentdisable_, other->dwauthentdisable_);
  std::swap(dwauthrealaward_, other->dwauthrealaward_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RealAuthParameter_s2c::GetMetadata() const {
  protobuf_RealAuthPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RealAuthPmd_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RealAuthParameter_s2c

// .NullPmd.response respcmd = 1;
bool RealAuthParameter_s2c::has_respcmd() const {
  return this != internal_default_instance() && respcmd_ != NULL;
}
void RealAuthParameter_s2c::clear_respcmd() {
  if (GetArenaNoVirtual() == NULL && respcmd_ != NULL) delete respcmd_;
  respcmd_ = NULL;
}
const ::NullPmd::response& RealAuthParameter_s2c::respcmd() const {
  // @@protoc_insertion_point(field_get:RealAuthPmd.RealAuthParameter_s2c.respcmd)
  return respcmd_ != NULL ? *respcmd_
                         : *::NullPmd::response::internal_default_instance();
}
::NullPmd::response* RealAuthParameter_s2c::mutable_respcmd() {
  
  if (respcmd_ == NULL) {
    respcmd_ = new ::NullPmd::response;
  }
  // @@protoc_insertion_point(field_mutable:RealAuthPmd.RealAuthParameter_s2c.respcmd)
  return respcmd_;
}
::NullPmd::response* RealAuthParameter_s2c::release_respcmd() {
  // @@protoc_insertion_point(field_release:RealAuthPmd.RealAuthParameter_s2c.respcmd)
  
  ::NullPmd::response* temp = respcmd_;
  respcmd_ = NULL;
  return temp;
}
void RealAuthParameter_s2c::set_allocated_respcmd(::NullPmd::response* respcmd) {
  delete respcmd_;
  respcmd_ = respcmd;
  if (respcmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:RealAuthPmd.RealAuthParameter_s2c.respcmd)
}

// uint64 dwauthentdisable = 2;
void RealAuthParameter_s2c::clear_dwauthentdisable() {
  dwauthentdisable_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 RealAuthParameter_s2c::dwauthentdisable() const {
  // @@protoc_insertion_point(field_get:RealAuthPmd.RealAuthParameter_s2c.dwauthentdisable)
  return dwauthentdisable_;
}
void RealAuthParameter_s2c::set_dwauthentdisable(::google::protobuf::uint64 value) {
  
  dwauthentdisable_ = value;
  // @@protoc_insertion_point(field_set:RealAuthPmd.RealAuthParameter_s2c.dwauthentdisable)
}

// uint64 dwauthrealaward = 3;
void RealAuthParameter_s2c::clear_dwauthrealaward() {
  dwauthrealaward_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 RealAuthParameter_s2c::dwauthrealaward() const {
  // @@protoc_insertion_point(field_get:RealAuthPmd.RealAuthParameter_s2c.dwauthrealaward)
  return dwauthrealaward_;
}
void RealAuthParameter_s2c::set_dwauthrealaward(::google::protobuf::uint64 value) {
  
  dwauthrealaward_ = value;
  // @@protoc_insertion_point(field_set:RealAuthPmd.RealAuthParameter_s2c.dwauthrealaward)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace RealAuthPmd

// @@protoc_insertion_point(global_scope)
